// Code generated by MockGen. DO NOT EDIT.
// Source: orderget.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	models "github.com/rycln/loyalsys/internal/models"
)

// MockgetAPI is a mock of getAPI interface.
type MockgetAPI struct {
	ctrl     *gomock.Controller
	recorder *MockgetAPIMockRecorder
}

// MockgetAPIMockRecorder is the mock recorder for MockgetAPI.
type MockgetAPIMockRecorder struct {
	mock *MockgetAPI
}

// NewMockgetAPI creates a new mock instance.
func NewMockgetAPI(ctrl *gomock.Controller) *MockgetAPI {
	mock := &MockgetAPI{ctrl: ctrl}
	mock.recorder = &MockgetAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockgetAPI) EXPECT() *MockgetAPIMockRecorder {
	return m.recorder
}

// GetOrderFromAccrual mocks base method.
func (m *MockgetAPI) GetOrderFromAccrual(arg0 context.Context, arg1 string) (*models.OrderAccrual, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderFromAccrual", arg0, arg1)
	ret0, _ := ret[0].(*models.OrderAccrual)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderFromAccrual indicates an expected call of GetOrderFromAccrual.
func (mr *MockgetAPIMockRecorder) GetOrderFromAccrual(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderFromAccrual", reflect.TypeOf((*MockgetAPI)(nil).GetOrderFromAccrual), arg0, arg1)
}

// MockgetStorager is a mock of getStorager interface.
type MockgetStorager struct {
	ctrl     *gomock.Controller
	recorder *MockgetStoragerMockRecorder
}

// MockgetStoragerMockRecorder is the mock recorder for MockgetStorager.
type MockgetStoragerMockRecorder struct {
	mock *MockgetStorager
}

// NewMockgetStorager creates a new mock instance.
func NewMockgetStorager(ctrl *gomock.Controller) *MockgetStorager {
	mock := &MockgetStorager{ctrl: ctrl}
	mock.recorder = &MockgetStoragerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockgetStorager) EXPECT() *MockgetStoragerMockRecorder {
	return m.recorder
}

// GetInconclusiveOrderNums mocks base method.
func (m *MockgetStorager) GetInconclusiveOrderNums(arg0 context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInconclusiveOrderNums", arg0)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInconclusiveOrderNums indicates an expected call of GetInconclusiveOrderNums.
func (mr *MockgetStoragerMockRecorder) GetInconclusiveOrderNums(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInconclusiveOrderNums", reflect.TypeOf((*MockgetStorager)(nil).GetInconclusiveOrderNums), arg0)
}

// MockerrRetryAfter is a mock of errRetryAfter interface.
type MockerrRetryAfter struct {
	ctrl     *gomock.Controller
	recorder *MockerrRetryAfterMockRecorder
}

// MockerrRetryAfterMockRecorder is the mock recorder for MockerrRetryAfter.
type MockerrRetryAfterMockRecorder struct {
	mock *MockerrRetryAfter
}

// NewMockerrRetryAfter creates a new mock instance.
func NewMockerrRetryAfter(ctrl *gomock.Controller) *MockerrRetryAfter {
	mock := &MockerrRetryAfter{ctrl: ctrl}
	mock.recorder = &MockerrRetryAfterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockerrRetryAfter) EXPECT() *MockerrRetryAfterMockRecorder {
	return m.recorder
}

// Error mocks base method.
func (m *MockerrRetryAfter) Error() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Error")
	ret0, _ := ret[0].(string)
	return ret0
}

// Error indicates an expected call of Error.
func (mr *MockerrRetryAfterMockRecorder) Error() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockerrRetryAfter)(nil).Error))
}

// GetRetryAfterDuration mocks base method.
func (m *MockerrRetryAfter) GetRetryAfterDuration() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRetryAfterDuration")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// GetRetryAfterDuration indicates an expected call of GetRetryAfterDuration.
func (mr *MockerrRetryAfterMockRecorder) GetRetryAfterDuration() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRetryAfterDuration", reflect.TypeOf((*MockerrRetryAfter)(nil).GetRetryAfterDuration))
}

// IsErrRetryAfter mocks base method.
func (m *MockerrRetryAfter) IsErrRetryAfter() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsErrRetryAfter")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsErrRetryAfter indicates an expected call of IsErrRetryAfter.
func (mr *MockerrRetryAfterMockRecorder) IsErrRetryAfter() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsErrRetryAfter", reflect.TypeOf((*MockerrRetryAfter)(nil).IsErrRetryAfter))
}
